# Generated by Django 4.1 on 2024-09-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('reg_no', models.CharField(max_length=5)),
                ('course', models.CharField(max_length=10)),
                ('date_joined', models.DateField()),
            ],
        ),
    ]
