# Generated by Django 4.1 on 2024-09-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(default='Fresher', max_length=15),
            preserve_default=False,
        ),
    ]
